services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./enginy
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - backend
