/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/CrearTaller': RouteRecordInfo<'/admin/CrearTaller', '/admin/CrearTaller', Record<never, never>, Record<never, never>>,
    '/admin/CrearUsuaris': RouteRecordInfo<'/admin/CrearUsuaris', '/admin/CrearUsuaris', Record<never, never>, Record<never, never>>,
    '/admin/Solicituds': RouteRecordInfo<'/admin/Solicituds', '/admin/Solicituds', Record<never, never>, Record<never, never>>,
    '/CrearSolicitud': RouteRecordInfo<'/CrearSolicitud', '/CrearSolicitud', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/pagesProfessor/paginaPrincipalProfessor': RouteRecordInfo<'/pagesProfessor/paginaPrincipalProfessor', '/pagesProfessor/paginaPrincipalProfessor', Record<never, never>, Record<never, never>>,
    '/pagesProfessor/TallersProfessor': RouteRecordInfo<'/pagesProfessor/TallersProfessor', '/pagesProfessor/TallersProfessor', Record<never, never>, Record<never, never>>,
    '/pagesProfessor/veureSolicituds': RouteRecordInfo<'/pagesProfessor/veureSolicituds', '/pagesProfessor/veureSolicituds', Record<never, never>, Record<never, never>>,
    '/paginaPrincipal': RouteRecordInfo<'/paginaPrincipal', '/paginaPrincipal', Record<never, never>, Record<never, never>>,
    '/Tallers': RouteRecordInfo<'/Tallers', '/Tallers', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/admin/CrearTaller.vue': {
      routes: '/admin/CrearTaller'
      views: never
    }
    'src/pages/admin/CrearUsuaris.vue': {
      routes: '/admin/CrearUsuaris'
      views: never
    }
    'src/pages/admin/Solicituds.vue': {
      routes: '/admin/Solicituds'
      views: never
    }
    'src/pages/CrearSolicitud.vue': {
      routes: '/CrearSolicitud'
      views: never
    }
    'src/pages/Login.vue': {
      routes: '/Login'
      views: never
    }
    'src/pages/pagesProfessor/paginaPrincipalProfessor.vue': {
      routes: '/pagesProfessor/paginaPrincipalProfessor'
      views: never
    }
    'src/pages/pagesProfessor/TallersProfessor.vue': {
      routes: '/pagesProfessor/TallersProfessor'
      views: never
    }
    'src/pages/pagesProfessor/veureSolicituds.vue': {
      routes: '/pagesProfessor/veureSolicituds'
      views: never
    }
    'src/pages/paginaPrincipal.vue': {
      routes: '/paginaPrincipal'
      views: never
    }
    'src/pages/Tallers.vue': {
      routes: '/Tallers'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
